/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AddProductC;


/**
 *
 * @author Deepak
 */
public class AddProduct extends javax.swing.JFrame {

    AddProductC add = new AddProductC();
    public AddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        APPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        PIDField = new javax.swing.JTextField();
        PIDLabel = new javax.swing.JLabel();
        PNameField = new javax.swing.JTextField();
        PNameLabel = new javax.swing.JLabel();
        PCatField = new javax.swing.JTextField();
        PCatLabel = new javax.swing.JLabel();
        PPriceField = new javax.swing.JTextField();
        PPriceLabel = new javax.swing.JLabel();
        PColorField = new javax.swing.JTextField();
        PColorLabel = new javax.swing.JLabel();
        bAddProduct = new javax.swing.JButton();
        PBrandField = new javax.swing.JTextField();
        PBrandLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Product Form");
        setLocation(new java.awt.Point(722, 97));
        setMaximumSize(new java.awt.Dimension(500, 620));
        setMinimumSize(new java.awt.Dimension(500, 620));
        setPreferredSize(new java.awt.Dimension(500, 585));
        setResizable(false);

        APPanel.setBackground(new java.awt.Color(243, 243, 243));

        TitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        TitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Add Product");
        TitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        PIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PIDLabel.setText("Product ID");

        PNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PNameLabel.setText("Product Name");

        PCatLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PCatLabel.setText("Product Category");

        PPriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PPriceLabel.setText("Price");

        PColorLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PColorLabel.setText("Color");

        bAddProduct.setBackground(new java.awt.Color(37, 99, 235));
        bAddProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        bAddProduct.setText("Add Product");
        bAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddProductActionPerformed(evt);
            }
        });

        PBrandLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PBrandLabel.setText("Brand");

        javax.swing.GroupLayout APPanelLayout = new javax.swing.GroupLayout(APPanel);
        APPanel.setLayout(APPanelLayout);
        APPanelLayout.setHorizontalGroup(
            APPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(APPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(APPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(APPanelLayout.createSequentialGroup()
                        .addGroup(APPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PCatField, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PCatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, APPanelLayout.createSequentialGroup()
                                .addGroup(APPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(PPriceField))
                                .addGap(33, 33, 33)
                                .addGroup(APPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PColorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(PColorField))
                                .addGap(43, 43, 43)
                                .addGroup(APPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PBrandField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PBrandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(APPanelLayout.createSequentialGroup()
                        .addGroup(APPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(APPanelLayout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(APPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(bAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        APPanelLayout.setVerticalGroup(
            APPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(APPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(PNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PCatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PCatField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(APPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PBrandLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(APPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PColorField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PBrandField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(bAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(APPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(APPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddProductActionPerformed
        String PID = PIDField.getText();
        String PName = PNameField.getText();
        String PCat = PCatField.getText();
        String Price = PPriceField.getText();
        String Color = PColorField.getText();
        String Brand = PBrandField.getText();
        
        add.Register(PID, PName, PCat, Price, Color, Brand);
        
        this.dispose();
        PIDField.setText("");
        PNameField.setText("");
        PCatField.setText("");
        PPriceField.setText("");
        PColorField.setText("");
        PBrandField.setText("");
        
    }//GEN-LAST:event_bAddProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel APPanel;
    private javax.swing.JTextField PBrandField;
    private javax.swing.JLabel PBrandLabel;
    private javax.swing.JTextField PCatField;
    private javax.swing.JLabel PCatLabel;
    private javax.swing.JTextField PColorField;
    private javax.swing.JLabel PColorLabel;
    private javax.swing.JTextField PIDField;
    private javax.swing.JLabel PIDLabel;
    private javax.swing.JTextField PNameField;
    private javax.swing.JLabel PNameLabel;
    private javax.swing.JTextField PPriceField;
    private javax.swing.JLabel PPriceLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton bAddProduct;
    // End of variables declaration//GEN-END:variables
}
