/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.LoginM;
import Controller.LoginC;

/**
 *
 * @author Deepak
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        LoginBox = new javax.swing.JPanel();
        TitleLable = new javax.swing.JLabel();
        UsernamePanel = new javax.swing.JPanel();
        UserIcon = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordPanel = new javax.swing.JPanel();
        PassIcon = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        TitleLogo = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        ViewPass = new javax.swing.JToggleButton();
        BLogin = new javax.swing.JButton();
        ForgotPass = new javax.swing.JLabel();
        Register = new javax.swing.JLabel();
        bgIMG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginBox.setBackground(new java.awt.Color(255, 255, 255));
        LoginBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginBox.setFocusable(false);
        LoginBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLable.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        TitleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLable.setText("The Paw Shop");
        LoginBox.add(TitleLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 210, 60));

        UsernamePanel.setBackground(new java.awt.Color(255, 255, 255));
        UsernamePanel.setPreferredSize(new java.awt.Dimension(71, 22));

        UserIcon.setBackground(new java.awt.Color(255, 255, 255));
        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/user.png"))); // NOI18N
        UserIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        UsernameField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        UsernameField.setSelectionColor(new java.awt.Color(204, 204, 204));
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsernamePanelLayout = new javax.swing.GroupLayout(UsernamePanel);
        UsernamePanel.setLayout(UsernamePanelLayout);
        UsernamePanelLayout.setHorizontalGroup(
            UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
        );
        UsernamePanelLayout.setVerticalGroup(
            UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsernamePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UsernameField)))
        );

        LoginBox.add(UsernamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 390, 50));

        PasswordPanel.setBackground(new java.awt.Color(255, 255, 255));
        PasswordPanel.setPreferredSize(new java.awt.Dimension(71, 22));

        PassIcon.setBackground(new java.awt.Color(255, 255, 255));
        PassIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/lock.png"))); // NOI18N
        PassIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        PassField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        PassField.setSelectionColor(new java.awt.Color(204, 204, 204));
        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PasswordPanelLayout = new javax.swing.GroupLayout(PasswordPanel);
        PasswordPanel.setLayout(PasswordPanelLayout);
        PasswordPanelLayout.setHorizontalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PassIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PasswordPanelLayout.setVerticalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PassIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PassField, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        LoginBox.add(PasswordPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 390, 50));

        TitleLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/pet-supplies (2).png"))); // NOI18N
        TitleLogo.setMinimumSize(new java.awt.Dimension(0, 0));
        TitleLogo.setName(""); // NOI18N
        LoginBox.add(TitleLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 28, -1, -1));

        PassLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 15)); // NOI18N
        PassLabel.setText("Password");
        LoginBox.add(PassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        UserLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 15)); // NOI18N
        UserLabel.setText("Username");
        LoginBox.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        ViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/eye-crossedW.png"))); // NOI18N
        ViewPass.setBorder(null);
        ViewPass.setFocusable(false);
        ViewPass.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/eyeW.png"))); // NOI18N
        ViewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewPassMouseExited(evt);
            }
        });
        ViewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPassActionPerformed(evt);
            }
        });
        LoginBox.add(ViewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 245, -1, -1));

        BLogin.setBackground(new java.awt.Color(0, 102, 102));
        BLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        BLogin.setForeground(new java.awt.Color(255, 255, 255));
        BLogin.setText("Login");
        BLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        BLogin.setBorderPainted(false);
        BLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });
        LoginBox.add(BLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 60, 30));

        ForgotPass.setFont(new java.awt.Font("Arial", 3, 13)); // NOI18N
        ForgotPass.setForeground(new java.awt.Color(0, 102, 102));
        ForgotPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForgotPass.setText("Forgot?");
        ForgotPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForgotPass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ForgotPass.setVisible(false);
        LoginBox.add(ForgotPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 60, -1));

        Register.setFont(new java.awt.Font("Arial", 3, 13)); // NOI18N
        Register.setForeground(new java.awt.Color(153, 153, 153));
        Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Register.setText("Register");
        Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegMouseExited(evt);
            }
        });
        LoginBox.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 112, 60, -1));

        bgPanel.add(LoginBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 160, 450, 365));

        bgIMG.setForeground(new java.awt.Color(204, 204, 204));
        bgIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/gradient.png"))); // NOI18N
        bgIMG.setText("jLabel1");
        bgIMG.setFocusable(false);
        bgIMG.setMinimumSize(new java.awt.Dimension(0, 0));
        bgIMG.setPreferredSize(new java.awt.Dimension(1280, 720));
        bgPanel.add(bgIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed

        
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void ViewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPassActionPerformed
     if(ViewPass.isSelected()){
         PassField.setEchoChar((char) 0);
    }
     else {PassField.setEchoChar('*');}
    }//GEN-LAST:event_ViewPassActionPerformed

    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
       LoginC C1 = new LoginC();
       String UN = UsernameField.getText();
       String PW = PassField.getText();
       C1.setLogin(UN,PW);
       
       
       
       
    }//GEN-LAST:event_BLoginActionPerformed

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        
    }//GEN-LAST:event_PassFieldActionPerformed

    private void RegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegMouseEntered
       Register.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_RegMouseEntered

    private void RegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegMouseClicked
        ManagerReg reg = new ManagerReg();
        this.setVisible(false);
        reg.setVisible(true);
    }//GEN-LAST:event_RegMouseClicked

    private void RegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegMouseExited
        Register.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_RegMouseExited

    private void ViewPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPassMouseEntered
        PassField.setEchoChar((char) 0);
    }//GEN-LAST:event_ViewPassMouseEntered

    private void ViewPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPassMouseExited
      if(ViewPass.isSelected()){
        PassField.setEchoChar((char) 0);}
      else {PassField.setEchoChar('*');}
    }//GEN-LAST:event_ViewPassMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BLogin;
    private javax.swing.JLabel ForgotPass;
    private javax.swing.JPanel LoginBox;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JLabel PassIcon;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JPanel PasswordPanel;
    private javax.swing.JLabel Register;
    private javax.swing.JLabel TitleLable;
    private javax.swing.JLabel TitleLogo;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JPanel UsernamePanel;
    private javax.swing.JToggleButton ViewPass;
    private javax.swing.JLabel bgIMG;
    private javax.swing.JPanel bgPanel;
    // End of variables declaration//GEN-END:variables
}
