/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Deepak
 */
public class ManagerReg extends javax.swing.JFrame {

    /**
     * Creates new form ManagerReg
     */
    public ManagerReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGPanel = new javax.swing.JPanel();
        Back_B = new javax.swing.JLabel();
        Mbox = new javax.swing.JPanel();
        mForumTitle = new javax.swing.JLabel();
        MField_H = new javax.swing.JPanel();
        mFname = new javax.swing.JTextField();
        mLname = new javax.swing.JTextField();
        mPass = new javax.swing.JTextField();
        mNIC = new javax.swing.JTextField();
        LNIC = new javax.swing.JLabel();
        LLname = new javax.swing.JLabel();
        LPass = new javax.swing.JLabel();
        LFname = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        BGPanel.setFocusable(false);
        BGPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        BGPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        BGPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/angle-double-left.png"))); // NOI18N
        Back_B.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back_BMouseClicked(evt);
            }
        });
        BGPanel.add(Back_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 40, 40));

        Mbox.setBackground(new java.awt.Color(255, 255, 255));
        Mbox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mForumTitle.setBackground(new java.awt.Color(255, 255, 255));
        mForumTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        mForumTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mForumTitle.setText("Manager Registration ");
        Mbox.add(mForumTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 36, 390, 60));

        MField_H.setBackground(new java.awt.Color(255, 255, 255));
        MField_H.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mFname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFnameActionPerformed(evt);
            }
        });
        MField_H.add(mFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 450, 48));

        mLname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        MField_H.add(mLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 104, 450, 48));

        mPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        MField_H.add(mPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, 450, 48));

        mNIC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        MField_H.add(mNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 450, 48));

        LNIC.setFont(new java.awt.Font("Leelawadee UI", 1, 15)); // NOI18N
        LNIC.setText("NIC");
        MField_H.add(LNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 180, 30));

        LLname.setFont(new java.awt.Font("Leelawadee UI", 1, 15)); // NOI18N
        LLname.setText("Last Name");
        MField_H.add(LLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 180, 30));

        LPass.setFont(new java.awt.Font("Leelawadee UI", 1, 15)); // NOI18N
        LPass.setText("Password");
        MField_H.add(LPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 180, 30));

        Mbox.add(MField_H, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 450, 360));

        LFname.setFont(new java.awt.Font("Leelawadee UI", 1, 15)); // NOI18N
        LFname.setText("First Name");
        Mbox.add(LFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 125, 180, 30));

        jButton1.setBackground(new java.awt.Color(22, 163, 74));
        jButton1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.setFocusable(false);
        Mbox.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 545, 390, 40));

        BGPanel.add(Mbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 530, 610));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/gradient.png"))); // NOI18N
        BG.setFocusable(false);
        BG.setMaximumSize(new java.awt.Dimension(1280, 720));
        BG.setMinimumSize(new java.awt.Dimension(1280, 720));
        BG.setName(""); // NOI18N
        BG.setPreferredSize(new java.awt.Dimension(1280, 720));
        BGPanel.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BGPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 527, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BGPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 268, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Back_BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_BMouseClicked
       LoginFrame LF = new LoginFrame();
        this.setVisible(false);
        LF.setVisible(true);
    }//GEN-LAST:event_Back_BMouseClicked

    private void mFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mFnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel BGPanel;
    private javax.swing.JLabel Back_B;
    private javax.swing.JLabel LFname;
    private javax.swing.JLabel LLname;
    private javax.swing.JLabel LNIC;
    private javax.swing.JLabel LPass;
    private javax.swing.JPanel MField_H;
    private javax.swing.JPanel Mbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField mFname;
    private javax.swing.JLabel mForumTitle;
    private javax.swing.JTextField mLname;
    private javax.swing.JTextField mNIC;
    private javax.swing.JTextField mPass;
    // End of variables declaration//GEN-END:variables
}
